# Configuration file for Jekyll
theme: jekyll-theme-minimal

title: Your Site Title
description: Your site description

# GitHub Pages settings
remote_theme: "pages-themes/minimal"
repository: naditraining/naditraining.github.io
branch: main
permalink: /:year/:month/:day/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - Rakefile
  - config.rb

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

plugins:
  - jekyll-feed

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

# Uncomment the following lines if you want to enable Google Analytics
# analytics_google:
#   id: UA-XXXXX-X
